export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_LOADING = 'FETCH_CHARACTERS_LOADING';
export const FETCH_CHARACTERS_ERROR = 'FETCH_CHARACTERS_ERROR';
export const FETCH_SINGLE_CHARACTER_SUCCESS = 'FETCH_SINGLE_CHARACTER_SUCCESS';
export const FETCH_SINGLE_CHARACTER_LOADING = 'FETCH_SINGLE_CHARACTER_LOADING';
export const FETCH_SINGLE_CHARACTER_ERROR = 'FETCH_SINGLE_CHARACTER_ERROR';
